import 'quest_model.dart';

final predefinedQuests = <QuestModel>[
  QuestModel(
    id: 'q1',
    title: 'First Step',
    description: 'Track every expense for 1 day',
    xp: 10,
    durationDays: 1,
    category: QuestCategory.basic,
  ),
  QuestModel(
    id: 'q2',
    title: 'Weekly Tracker',
    description: 'Log your expenses for 7 days',
    xp: 30,
    durationDays: 7,
    category: QuestCategory.basic,
  ),
  QuestModel(
    id: 'q3',
    title: 'Coffee Check',
    description: 'Skip buying coffee for a day',
    xp: 15,
    durationDays: 1,
    category: QuestCategory.basic,
  ),
  QuestModel(
    id: 'q4',
    title: 'Budget Starter',
    description: 'Set a monthly budget',
    xp: 20,
    durationDays: null,
    category: QuestCategory.basic,
  ),
  QuestModel(
    id: 'q5',
    title: 'Receipt Collector',
    description: 'Save all receipts for 3 days',
    xp: 20,
    durationDays: 3,
    category: QuestCategory.basic,
  ),
  QuestModel(
    id: 'q6',
    title: 'Cash Snapshot',
    description:
        'Write down how much cash and money in accounts you have today',
    xp: 10,
    durationDays: null,
    category: QuestCategory.basic,
  ),
  QuestModel(
    id: 'q7',
    title: 'Goal Setter',
    description: 'Set one financial goal',
    xp: 15,
    durationDays: null,
    category: QuestCategory.basic,
  ),
  QuestModel(
    id: 'q8',
    title: 'Wallet Check',
    description: 'List all your current debts',
    xp: 25,
    durationDays: null,
    category: QuestCategory.basic,
  ),
  QuestModel(
    id: 'q9',
    title: 'Subscription Audit',
    description: 'Identify 3 unused subscriptions',
    xp: 30,
    durationDays: null,
    category: QuestCategory.basic,
  ),
  QuestModel(
    id: 'q10',
    title: 'Daily Check-In',
    description: 'Open the app 5 days in a row',
    xp: 15,
    durationDays: 5,
    category: QuestCategory.basic,
  ),
  QuestModel(
    id: 'q11',
    title: 'No Fast Food',
    description: 'Avoid fast food for 30 days',
    xp: 80,
    durationDays: 30,
    category: QuestCategory.difficult,
  ),
  QuestModel(
    id: 'q12',
    title: 'Credit Card Freeze',
    description: 'Don’t use any credit card for 30 days',
    xp: 90,
    durationDays: 30,
    category: QuestCategory.difficult,
  ),
  QuestModel(
    id: 'q13',
    title: 'Savings Sprint',
    description: 'Save \$100 in one week',
    xp: 70,
    durationDays: 7,
    category: QuestCategory.difficult,
  ),
  QuestModel(
    id: 'q14',
    title: 'Budget Warrior',
    description: 'Spend 10% less than your budget',
    xp: 60,
    durationDays: 30,
    category: QuestCategory.difficult,
  ),
  QuestModel(
    id: 'q15',
    title: 'Daily Tracker Pro',
    description: 'Log expenses every day for a month',
    xp: 75,
    durationDays: 30,
    category: QuestCategory.difficult,
  ),
  QuestModel(
    id: 'q16',
    title: 'Zero Impulse',
    description: 'No unplanned purchases for 14 days',
    xp: 60,
    durationDays: 14,
    category: QuestCategory.difficult,
  ),
  QuestModel(
    id: 'q17',
    title: 'Weekly Review',
    description: 'Review finances every Sunday for a month',
    xp: 50,
    durationDays: 28,
    category: QuestCategory.difficult,
  ),
  QuestModel(
    id: 'q18',
    title: 'Emergency Fund Starter',
    description: 'Set aside \$300 in a month',
    xp: 70,
    durationDays: 30,
    category: QuestCategory.difficult,
  ),
  QuestModel(
    id: 'q19',
    title: 'Total Transparency',
    description: 'Share your budget with a partner',
    xp: 55,
    durationDays: null,
    category: QuestCategory.difficult,
  ),
  QuestModel(
    id: 'q20',
    title: 'Save \$1000',
    description: 'Accumulate \$1000 over 2 months',
    xp: 100,
    durationDays: 60,
    category: QuestCategory.difficult,
  ),
  QuestModel(
    id: 'q21',
    title: 'Family Budget',
    description: 'Create a joint family budget',
    xp: 40,
    durationDays: null,
    category: QuestCategory.family,
  ),
  QuestModel(
    id: 'q22',
    title: 'Grocery Challenge',
    description: 'Shop under \$100 for a week',
    xp: 45,
    durationDays: 7,
    category: QuestCategory.family,
  ),
  QuestModel(
    id: 'q23',
    title: 'Talk Money',
    description: 'Discuss money goals with partner',
    xp: 30,
    durationDays: null,
    category: QuestCategory.family,
  ),
  QuestModel(
    id: 'q24',
    title: 'Kids & Coins',
    description: 'Teach a child to save \$10',
    xp: 40,
    durationDays: null,
    category: QuestCategory.family,
  ),
  QuestModel(
    id: 'q25',
    title: 'Team Saving',
    description: 'Save \$200 together',
    xp: 50,
    durationDays: 14,
    category: QuestCategory.family,
  ),
  QuestModel(
    id: 'q26',
    title: 'Weekly Sync',
    description: 'Do 4 weekly family budget check-ins',
    xp: 60,
    durationDays: 28,
    category: QuestCategory.family,
  ),
  QuestModel(
    id: 'q27',
    title: 'Meal Prep',
    description: 'Cook at home 5 days/week for a month',
    xp: 70,
    durationDays: 28,
    category: QuestCategory.family,
  ),
  QuestModel(
    id: 'q28',
    title: 'Debt-Free Duo',
    description: 'Pay off a joint debt',
    xp: 80,
    durationDays: null,
    category: QuestCategory.family,
  ),
  QuestModel(
    id: 'q29',
    title: 'Bill Splitter',
    description: 'Organize and share household bills',
    xp: 35,
    durationDays: null,
    category: QuestCategory.family,
  ),
  QuestModel(
    id: 'q30',
    title: 'Over-Budget Lockdown',
    description: 'Avoid overspending for a full month',
    xp: 160,
    durationDays: 30,
    category: QuestCategory.family,
  ),
  QuestModel(
    id: 'q31',
    title: 'First Stock',
    description: 'Buy your first stock',
    xp: 60,
    durationDays: null,
    category: QuestCategory.investments,
  ),
  QuestModel(
    id: 'q32',
    title: 'Index Explorer',
    description: 'Research 3 index funds',
    xp: 35,
    durationDays: null,
    category: QuestCategory.investments,
  ),
  QuestModel(
    id: 'q33',
    title: 'Paper Portfolio',
    description: 'Build a mock investment portfolio',
    xp: 30,
    durationDays: null,
    category: QuestCategory.investments,
  ),
  QuestModel(
    id: 'q34',
    title: 'ETF Hunt',
    description: 'Learn and bookmark 5 ETFs',
    xp: 25,
    durationDays: null,
    category: QuestCategory.investments,
  ),
  QuestModel(
    id: 'q35',
    title: 'Watchlist Setup',
    description: 'Add 5 stocks to a watchlist',
    xp: 20,
    durationDays: null,
    category: QuestCategory.investments,
  ),
  QuestModel(
    id: 'q36',
    title: 'Investment Plan',
    description: 'Write down your investment strategy',
    xp: 40,
    durationDays: null,
    category: QuestCategory.investments,
  ),
  QuestModel(
    id: 'q37',
    title: 'Investment Reading',
    description: 'Read 3 articles on investing',
    xp: 30,
    durationDays: null,
    category: QuestCategory.investments,
  ),
  QuestModel(
    id: 'q38',
    title: 'Crypto Curious',
    description: 'Research 2 cryptocurrencies',
    xp: 25,
    durationDays: null,
    category: QuestCategory.investments,
  ),
  QuestModel(
    id: 'q39',
    title: 'Monthly Investment',
    description: 'Invest \$50 this month',
    xp: 50,
    durationDays: 30,
    category: QuestCategory.investments,
  ),
  QuestModel(
    id: 'q40',
    title: 'Passive Income Dream',
    description: 'Learn 3 passive income ideas',
    xp: 30,
    durationDays: null,
    category: QuestCategory.investments,
  )
];
